name: driving_simulator
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - tensorboard
  - opencv
  - pip:
    - pytorch-lightning
    - omegaconf
    - einops
    - -e .